services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATA_CSV_PATH: /app/data.csv
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/cereal_api
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: secret
      SERVER_PORT: "8080"
    ports:
      - "8080:8080"
    restart: unless-stopped

  database:
    image: mysql:latest
    container_name: my_database
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cereal_api
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - ./import:/var/lib/mysql-files
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db-data:




#docker compose up -d --build
#docker compose ps
#docker compose logs -f app
#docker compose down
#docker compose down -v