# Triggers
# - on push to dev: run tests, then create/update PR into main if none is open
# - on pull_request to main: run rests for the PR

name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # run on all triggers
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - uses: actions/checkout@v4

      # setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: maven

      # build
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # test
      - name: Run tests
        run: mvn test

  open-pr: